import React,{useState,useMemo}from"react";
import{createRoot}from"react-dom/client";
import{BrowserRouter,Routes,Route,Link,useParams,useNavigate}from"react-router-dom";
import"./styles.css";

const products=[
{id:1,name:"Laptop",category:"Electronics",price:55000,stock:10,image:"/images/laptop.jpg",description:"A powerful laptop suitable for students, professionals and everyday computing."},
{id:2,name:"Wireless Mouse",category:"Electronics",price:800,stock:25,image:"/images/mouse.jpg",description:"Comfortable wireless mouse with accurate tracking and ergonomic design."},
{id:3,name:"Office Chair",category:"Furniture",price:4500,stock:8,image:"/images/chair.jpg",description:"Comfortable office chair designed for long working and study sessions."},
{id:4,name:"Notebook",category:"Stationery",price:100,stock:50,image:"/images/notebook.jpg",description:"Premium quality notebook suitable for college notes and daily writing."},
{id:5,name:"Mechanical Keyboard",category:"Electronics",price:2500,stock:15,image:"/images/keyboard.jpg",description:"Mechanical keyboard with comfortable keys and a modern compact design."},
{id:6,name:"Study Table",category:"Furniture",price:6500,stock:6,image:"/images/table.jpg",description:"Modern study table with enough space for books, laptop and accessories."},
{id:7,name:"Pen Set",category:"Stationery",price:150,stock:40,image:"/images/pens.jpg",description:"Smooth writing pen set suitable for students and office work."},
{id:8,name:"Headphones",category:"Electronics",price:1800,stock:20,image:"/images/headphones.jpg",description:"Comfortable headphones with immersive sound for music and online classes."}
];
const money=n=>`₹${n.toLocaleString("en-IN")}`;

function Navbar({count}){return <header className="topbar"><div className="nav-inner"><Link to="/" className="brand">PRODUCT<span>STORE</span></Link><nav><Link to="/">Home</Link><Link to="/products">Products</Link><Link to="/cart" className="cart-nav">🛒 <b>{count}</b></Link></nav></div></header>}
function Footer(){return <footer className="footer"><strong>PRODUCT<span>STORE</span></strong><small>Your simple online shopping solution.</small><small>React Product Inventory & Shopping Cart<br/>Created for AWT Assignment</small></footer>}
function Home(){return <><section className="hero"><div className="hero-photo"/><div className="hero-copy"><div className="eyebrow">WELCOME TO</div><h1>PRODUCT<br/><span>STORE</span></h1><p>Discover electronics, furniture and stationery products at affordable prices.</p><Link className="gold-btn" to="/products">Explore Products <span>→</span></Link></div><div className="hero-panel"><div className="round-cart">🛒</div><h2>Everything You Need</h2><p>Browse products, filter categories, add items to your cart and checkout easily.</p></div></section><section className="feature-strip"><Feature icon="◈" title="Quality Products" text="Choose from a variety of products."/><Feature icon="⌕" title="Easy Search" text="Find products quickly using search."/><Feature icon="🛒" title="Shopping Cart" text="Manage your cart and quantities easily."/><Feature icon="▣" title="Easy Checkout" text="Complete your order using the checkout form."/></section></>}
function Feature({icon,title,text}){return <div className="feature"><div className="feature-icon">{icon}</div><h3>{title}</h3><p>{text}</p></div>}
function ProductCard({product,addToCart}){return <article className="product-card"><div className="card-img"><img src={product.image} alt={product.name}/><span>{product.category}</span></div><div className="card-body"><h3>{product.name}</h3><p className="muted">{product.description}</p><div className="price-row"><strong>{money(product.price)}</strong><small>Stock: {product.stock}</small></div><div className="card-actions"><Link to={`/products/${product.id}`} className="outline-btn">View Details</Link><button className="dark-btn" onClick={()=>addToCart(product)}>Add to Cart</button></div></div></article>}
function Products({addToCart}){const[search,setSearch]=useState("");const[category,setCategory]=useState("All");const categories=["All",...new Set(products.map(p=>p.category))];const filtered=useMemo(()=>products.filter(p=>p.name.toLowerCase().includes(search.toLowerCase())&&(category==="All"||p.category===category)),[search,category]);return <div className="page"><div className="page-title"><div className="eyebrow">OUR COLLECTION</div><h1>Products</h1><p>Browse our complete product inventory</p></div><div className="filters"><div><label>Search Products</label><div className="input-wrap"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search laptop, mouse, notebook..."/></div></div><div><label>Category</label><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></div></div><div className="result-row"><span>Showing <b>{filtered.length}</b> products</span>{search&&<button onClick={()=>setSearch("")}>Clear Search</button>}</div>{filtered.length?<div className="products-grid">{filtered.map(p=><ProductCard key={p.id} product={p} addToCart={addToCart}/>)}</div>:<div className="empty-box"><div>⌕</div><h2>No Products Found</h2><p>Try another search.</p></div>}</div>}
function ProductDetails({addToCart}){const{id}=useParams();const p=products.find(x=>x.id===Number(id));if(!p)return <div className="empty-box"><h2>Product Not Found</h2><Link to="/products" className="gold-btn">Back to Products</Link></div>;return <div className="page"><Link to="/products" className="back">← Back to Products</Link><div className="details"><div className="details-image"><img src={p.image} alt={p.name}/></div><div className="details-copy"><span className="detail-tag">{p.category}</span><h1>{p.name}</h1><div className="detail-price">{money(p.price)}</div><p>{p.description}</p><div className="detail-info"><div><small>Product ID</small><b>#{p.id}</b></div><div><small>Available Quantity</small><b>{p.stock}</b></div><div><small>Category</small><b>{p.category}</b></div></div><button className="big-gold" onClick={()=>addToCart(p)}>🛒 Add to Cart</button></div></div></div>}
function Cart({cart,inc,dec,remove,clear}){const[checkout,setCheckout]=useState(false);const[form,setForm]=useState({name:"",email:"",address:""});const navigate=useNavigate();const count=cart.reduce((s,i)=>s+i.cartQuantity,0);const total=cart.reduce((s,i)=>s+i.price*i.cartQuantity,0);if(!cart.length)return <div className="empty-cart"><div className="empty-round">🛒</div><h1>Your Cart is Empty</h1><p>You haven't added any products to your cart yet.</p><Link className="gold-btn" to="/products">Start Shopping</Link></div>;const submit=e=>{e.preventDefault();alert(`Thank you ${form.name}! Your order has been placed successfully.`);clear();setCheckout(false);navigate("/cart")};return <div className="page"><div className="page-title"><div className="eyebrow">SHOPPING CART</div><h1>Your Cart</h1><p>{count} item{count!==1?"s":""} in your cart</p></div><div className="cart-layout"><div className="cart-list">{cart.map(i=><div className="cart-item" key={i.id}><img src={i.image} alt={i.name}/><div className="cart-name"><small>{i.category}</small><h3>{i.name}</h3><span>{money(i.price)}</span></div><div className="qty"><button onClick={()=>dec(i.id)}>−</button><b>{i.cartQuantity}</b><button onClick={()=>inc(i.id)}>+</button></div><strong className="line-total">{money(i.price*i.cartQuantity)}</strong><button className="remove" onClick={()=>remove(i.id)}>×</button></div>)}</div><aside className="summary"><h2>Order Summary</h2><div><span>Items</span><span>{count}</span></div><div><span>Subtotal</span><span>{money(total)}</span></div><div><span>Delivery</span><b className="free">FREE</b></div><hr/><div className="summary-total"><span>Total</span><b>{money(total)}</b></div><button className="checkout" onClick={()=>setCheckout(true)}>Proceed to Checkout</button><button className="clear" onClick={clear}>Clear Cart</button></aside></div>{checkout&&<div className="modal-bg"><div className="modal"><button className="modal-x" onClick={()=>setCheckout(false)}>×</button><h2>Checkout</h2><p>Enter your details to complete your order.</p><form onSubmit={submit}><label>Full Name</label><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Enter your name"/><label>Email</label><input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="Enter your email"/><label>Address</label><textarea required value={form.address} onChange={e=>setForm({...form,address:e.target.value})} placeholder="Enter delivery address"/><button className="place" type="submit">Place Order</button></form></div></div>}</div>}

function App(){const[cart,setCart]=useState([]);const addToCart=p=>setCart(c=>{const f=c.find(i=>i.id===p.id);return f?c.map(i=>i.id===p.id&&i.cartQuantity<p.stock?{...i,cartQuantity:i.cartQuantity+1}:i):[...c,{...p,cartQuantity:1}]});const inc=id=>setCart(c=>c.map(i=>i.id===id&&i.cartQuantity<i.stock?{...i,cartQuantity:i.cartQuantity+1}:i));const dec=id=>setCart(c=>c.map(i=>i.id===id?{...i,cartQuantity:i.cartQuantity-1}:i).filter(i=>i.cartQuantity>0));const remove=id=>setCart(c=>c.filter(i=>i.id!==id));const clear=()=>setCart([]);const count=cart.reduce((s,i)=>s+i.cartQuantity,0);return <BrowserRouter><Navbar count={count}/><Routes><Route path="/" element={<Home/>}/><Route path="/products" element={<Products addToCart={addToCart}/>}/><Route path="/products/:id" element={<ProductDetails addToCart={addToCart}/>}/><Route path="/cart" element={<Cart cart={cart} inc={inc} dec={dec} remove={remove} clear={clear}/>}/></Routes><Footer/></BrowserRouter>}
createRoot(document.getElementById("root")).render(<App/>);